import { MenuItem, NewsItem, User } from "./types";

import {
  Newspaper,
  AlertTriangle,
  FileText,
  ShieldPlus,
  Stethoscope,
  MessageCircleHeart,
  FileHeart,
  Building2,
  Ambulance,
  Laptop2,
  HeartHandshake,
  Award,
  Home,
  Info,
  Users,
  Utensils,
  Syringe,
  CalendarDays,
  Search,
} from "lucide-react";

export const users: Omit<User, "role">[] = [
  { full_name: "TS.BS Nguyễn Trọng Diện – Giám đốc", id: 1 },
  { full_name: "TS. Nguyễn Đình Hưng – Phó Giám đốc", id: 2 },
  { full_name: "TS. Trần Văn Chung – Phó Giám đốc", id: 3 },
  { full_name: "TS. Ông Vũ Cao Cương – Phó Giám đốc", id: 4 },
  { full_name: "Đ/c Đinh Hồng Phong  – Phó Giám đốc", id: 5 },
];

export const SERVICE_CATEGORIES = [
  {
    id: 1,
    title: "Tin tức – Sự kiện y tế",
    path: "/news/events",
    icon: Newspaper,
    containerClass:
      "bg-gradient-to-br from-blue-50 via-blue-100 to-blue-50 border-blue-200 hover:shadow-blue-300",
    iconBoxClass: "bg-blue-600 text-white shadow-blue-400/50",
    titleClass: "text-blue-900",
  },
  {
    id: 2,
    title: "Lịch công tác",
    // path: "http://lichcongtac.qnict.vn/sythanoi/",
    path: "/schedule",
    icon: CalendarDays,
    containerClass:
      "bg-gradient-to-br from-orange-50 via-orange-100 to-orange-50 border-orange-200 hover:shadow-orange-300",
    iconBoxClass: "bg-orange-500 text-white shadow-orange-400/50",
    titleClass: "text-orange-900",
  },
  {
    id: 3,
    title: "Chính sách y tế – Bảo hiểm y tế",
    path: "/policy",
    icon: FileText,
    containerClass:
      "bg-gradient-to-br from-indigo-50 via-indigo-100 to-indigo-50 border-indigo-200 hover:shadow-indigo-300",
    iconBoxClass: "bg-indigo-600 text-white shadow-indigo-400/50",
    titleClass: "text-indigo-900",
  },
  {
    id: 4,
    title: "Phòng bệnh – Nâng cao sức khỏe",
    path: "/news/prevention",
    icon: ShieldPlus,
    containerClass:
      "bg-gradient-to-br from-emerald-50 via-emerald-100 to-emerald-50 border-emerald-200 hover:shadow-emerald-300",
    iconBoxClass: "bg-emerald-600 text-white shadow-emerald-400/50",
    titleClass: "text-emerald-900",
  },
  {
    id: 5,
    title: "Khám bệnh - chữa bệnh",
    path: "/news/examination",
    icon: Stethoscope,
    containerClass:
      "bg-gradient-to-br from-cyan-50 via-cyan-100 to-cyan-50 border-cyan-200 hover:shadow-cyan-300",
    iconBoxClass: "bg-cyan-600 text-white shadow-cyan-400/50",
    titleClass: "text-cyan-900",
  },
  {
    id: 6,
    title: "Tư vấn sức khỏe",
    path: "/consulting",
    icon: MessageCircleHeart,
    containerClass:
      "bg-gradient-to-br from-pink-50 via-pink-100 to-pink-50 border-pink-200 hover:shadow-pink-300",
    iconBoxClass: "bg-pink-500 text-white shadow-pink-400/50",
    titleClass: "text-pink-900",
  },
  {
    id: 7,
    title: "Hồ sơ sức khỏe toàn dân",
    path: "/health-records",
    icon: FileHeart,
    containerClass:
      "bg-gradient-to-br from-sky-50 via-sky-100 to-sky-50 border-sky-200 hover:shadow-sky-300",
    iconBoxClass: "bg-sky-600 text-white shadow-sky-400/50",
    titleClass: "text-sky-900",
  },
  {
    id: 8,
    title: "Hệ thống y tế Thủ đô",
    path: "/hanoi-system",
    icon: Building2,
    containerClass:
      "bg-gradient-to-br from-slate-50 via-slate-100 to-slate-50 border-slate-200 hover:shadow-slate-300",
    iconBoxClass: "bg-slate-600 text-white shadow-slate-400/50",
    titleClass: "text-slate-900",
  },
  {
    id: 9,
    title: "Trung tâm điều hành cấp cứu thông minh",
    path: "/emergency",
    icon: Ambulance,
    containerClass:
      "bg-gradient-to-br from-red-50 via-red-100 to-red-50 border-red-200 hover:shadow-red-300",
    iconBoxClass: "bg-red-600 text-white shadow-red-400/50",
    titleClass: "text-red-900",
  },
  {
    id: 10,
    title: "Chuyển đổi số",
    path: "/data-lookup",
    icon: Search,
    containerClass:
      "bg-gradient-to-br from-violet-50 via-violet-100 to-violet-50 border-violet-200 hover:shadow-violet-300",
    iconBoxClass: "bg-violet-600 text-white shadow-violet-400/50",
    titleClass: "text-violet-900",
  },
  {
    id: 11,
    title: "Bảo trợ xã hội",
    path: "/news/social",
    icon: HeartHandshake,
    containerClass:
      "bg-gradient-to-br from-teal-50 via-teal-100 to-teal-50 border-teal-200 hover:shadow-teal-300",
    iconBoxClass: "bg-teal-600 text-white shadow-teal-400/50",
    titleClass: "text-teal-900",
  },
  {
    id: 12,
    title: "Gương người tốt – việc tốt ngành Y",
    path: "/news/good-deeds",
    icon: Award,
    containerClass:
      "bg-gradient-to-br from-yellow-50 via-yellow-100 to-yellow-50 border-yellow-200 hover:shadow-yellow-300",
    iconBoxClass: "bg-yellow-500 text-white shadow-yellow-400/50",
    titleClass: "text-yellow-900",
  },
];
export const SERVICE_CATEGORIES_FILTER = [
  {
    id: 1,
    title: "Tin tức – Sự kiện y tế",
    path: "/news/events",
  },
  {
    id: 2,
    title: "Cảnh báo y tế – Truyền thông nguy cơ",
    path: "/news/alerts",
  },
  {
    id: 3,
    title: "Khám bệnh - chữa bệnh",
    path: "/examination",
  },
  {
    id: 4,
    title: "Phòng bệnh – Nâng cao sức khỏe",
    path: "/news/prevention",
  },
  {
    id: 5,
    title: "Bảo trợ xã hội",
    path: "/news/examination",
  },
  {
    id: 6,
    title: "Chuyển đổi số",
    path: "/consulting",
  },
  {
    id: 7,
    title: "Chính sách y tế - bảo hiểm y tế",
    path: "/health-records",
  },
  {
    id: 8,
    title: "Gương người tốt – việc tốt ngành Y",
    path: "/good-deeds",
  },
];
export const MOCK_VIDEOS = [
  {
    id: "v1",
    title:
      "Bản tin Y tế Hà Nội: Toàn cảnh công tác phòng chống dịch tuần 1 tháng 1/2026",
    duration: "05:30",
    thumbnail: "https://picsum.photos/seed/video1/800/450",
    date: "07/01/2026",
  },
  {
    id: "v2",
    title:
      "Phóng sự: Những chiến sĩ áo trắng thầm lặng đêm Giao thừa Tết Bính Ngọ",
    duration: "08:45",
    thumbnail: "https://picsum.photos/seed/video2/800/450",
    date: "10/01/2026",
  },
  {
    id: "v3",
    title: "Hướng dẫn người dân sử dụng ứng dụng Hồ sơ sức khỏe điện tử",
    duration: "03:15",
    thumbnail: "https://picsum.photos/seed/video3/800/450",
    date: "02/01/2026",
  },
  {
    id: "v4",
    title: "Tọa đàm: Nâng cao chất lượng khám chữa bệnh tại y tế cơ sở",
    duration: "15:20",
    thumbnail: "https://picsum.photos/seed/video4/800/450",
    date: "28/12/2025",
  },
  {
    id: "v5",
    title: "Chuyên mục Sức khỏe: Phòng chống bệnh tiểu đường",
    duration: "10:00",
    thumbnail: "https://picsum.photos/seed/video5/800/450",
    date: "25/12/2025",
  },
];

export const MAIN_MENU: MenuItem[] = [
  { id: "home", title: "Trang chủ", path: "/", icon: Home },
  {
    id: "news",
    title: "Tin tức",
    path: "/news/events",
    icon: Newspaper,
    children: [
      {
        id: "news-events",
        title: "Tin tức – Sự kiện y tế",
        path: "/news/events",

        icon: Newspaper,
      },
      {
        id: "alerts",
        title: "Cảnh báo y tế - Truyền thông nguy cơ",
        path: "/news/alerts",
        icon: AlertTriangle,
      },
      {
        id: "good-deeds",
        title: "Gương người tốt – việc tốt",
        path: "/news/good-deeds",
        icon: Award,
      },
    ],
  },
  {
    id: "medical-pro",
    title: "Khám chữa bệnh",
    path: "/news/examination",
    icon: Stethoscope,
    children: [
      {
        id: "exam-general",
        title: "Thông tin khám chữa bệnh",
        path: "/news/examination",
        icon: Stethoscope,
      },
      {
        id: "food-safety",
        title: "Tư vấn sức khỏe",
        path: "/consulting",
        icon: Utensils,
      },
      {
        id: "population",
        title: "Hồ sơ sức khỏe toàn dân",
        path: "/health-records",
        icon: Users,
      },
    ],
  },
  { id: "policy", title: "Chính sách - BHYT", path: "/policy", icon: Info },
  {
    id: "system",
    title: "Hệ thống y tế",
    path: "/hanoi-system",
    icon: Building2,
    children: [
      {
        id: "system-network",
        title: "Mạng lưới cơ sở y tế",
        path: "/hanoi-system",
        icon: Building2,
      },
      {
        id: "emergency",
        title: "Trung tâm cấp cứu thông minh",
        path: "/emergency",
        icon: Ambulance,
      },
    ],
  },
  {
    id: "digital",
    title: "Chuyển đổi số",
    path: "/data-lookup",
    icon: Laptop2,
  },
  {
    id: "social-security",
    title: "An sinh xã hội",
    path: "/social-security",
    icon: Info,
  },
  {
    id: "guide",
    title: "Giới thiệu/Liên hệ",
    path: "#",
    icon: HeartHandshake,
    children: [
      {
        id: "work-schedule",
        // linkUrl :"http://lichcongtac.qnict.vn/sythanoi/",
        title: "Lịch công tác",
        path: "/schedule",
        icon: CalendarDays,
      },
      {
        id: "guide-exam",
        title: "Quy trình khám bệnh",
        path: "/guide/exam",
        icon: FileText,
      },
      {
        id: "guide-insurance",
        title: "Bảo hiểm y tế",
        path: "/policy",
        icon: ShieldPlus,
      },
      {
        id: "guide-vaccine",
        title: "Lịch tiêm chủng",
        path: "/guide/vaccine",
        icon: Syringe,
      },
    ],
  },
];

export const MOCK_NEWS: NewsItem[] = [
  {
    id: 1,
    title: "Hà Nội triển khai thí điểm hồ sơ sức khỏe điện tử toàn dân",
    excerpt:
      "Sở Y tế Hà Nội vừa ban hành kế hoạch triển khai thí điểm lập hồ sơ sức khỏe điện tử cho người dân trên địa bàn 30 quận, huyện, thị xã nhằm nâng cao chất lượng quản lý sức khỏe cộng đồng.",
    date: "12/05/2024",
    image: "https://chuyendoiso.quangngai.gov.vn/items/cms/4347.jpg",
    category: "news-events",
    isFeatured: true,
  },
  {
    id: 2,
    title:
      "Cảnh báo dịch sốt xuất huyết có xu hướng gia tăng tại một số quận huyện",
    excerpt:
      "Theo Trung tâm Kiểm soát bệnh tật (CDC) Hà Nội, số ca mắc sốt xuất huyết trên địa bàn thành phố đang có dấu hiệu tăng nhanh tại các khu vực dân cư đông đúc.",
    date: "11/05/2024",
    image:
      "https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?q=80&w=800&auto=format&fit=crop",
    category: "alerts",
  },
  {
    id: 3,
    title: "Bác sĩ Bệnh viện Xanh Pôn cứu sống bệnh nhân bị vỡ tạng do tai nạn",
    excerpt:
      "Các bác sĩ Khoa Ngoại tiêu hóa, Bệnh viện Đa khoa Xanh Pôn vừa thực hiện thành công ca phẫu thuật cấp cứu cho một bệnh nhân bị chấn thương bụng kín nghiêm trọng.",
    date: "10/05/2024",
    image:
      "https://images.unsplash.com/photo-1551076805-e1869033e561?q=80&w=800&auto=format&fit=crop",
    category: "good-deeds",
  },
  {
    id: 4,
    title:
      "Hà Nội tăng cường kiểm tra an toàn thực phẩm tại các bếp ăn trường học",
    excerpt:
      "Sở Y tế phối hợp với Sở Giáo dục và Đào tạo Hà Nội thành lập các đoàn kiểm tra liên ngành nhằm đảm bảo an toàn vệ sinh thực phẩm cho học sinh.",
    date: "09/05/2024",
    image:
      "https://images.unsplash.com/photo-1547573854-74d2a71d0826?q=80&w=800&auto=format&fit=crop",
    category: "news-events",
  },
  {
    id: 5,
    title:
      "Khám bệnh, phát thuốc miễn phí cho người cao tuổi tại huyện Sóc Sơn",
    excerpt:
      "Hơn 500 người cao tuổi tại xã Minh Phú, huyện Sóc Sơn đã được các y bác sĩ tình nguyện khám bệnh, tư vấn sức khỏe và cấp phát thuốc miễn phí.",
    date: "08/05/2024",
    image:
      "https://images.unsplash.com/photo-1581056771107-24ca5f033842?q=80&w=800&auto=format&fit=crop",
    category: "social",
  },
  {
    id: 6,
    title: "Thủ tục đăng ký bảo hiểm y tế hộ gia đình trực tuyến",
    excerpt:
      "Hướng dẫn chi tiết các bước đăng ký tham gia bảo hiểm y tế hộ gia đình qua cổng dịch vụ công quốc gia và ứng dụng VssID.",
    date: "07/05/2024",
    image:
      "https://images.unsplash.com/photo-1454165205744-3b78555e5572?q=80&w=800&auto=format&fit=crop",
    category: "policy",
  },
  {
    id: 7,
    title: "Lợi ích của việc tiêm chủng mở rộng đối với trẻ em",
    excerpt:
      "Tiêm chủng là biện pháp hiệu quả nhất để phòng ngừa các bệnh truyền nhiễm nguy hiểm ở trẻ nhỏ, giúp xây dựng hệ miễn dịch cộng đồng vững mạnh.",
    date: "06/05/2024",
    image:
      "https://images.unsplash.com/photo-1584362946444-1e7c4f9b7113?q=80&w=800&auto=format&fit=crop",
    category: "prevention",
  },
  {
    id: 8,
    title: "Chuyển đổi số ngành y tế: Bước tiến mới trong quản lý bệnh viện",
    excerpt:
      "Việc áp dụng bệnh án điện tử và hệ thống quản lý thông tin bệnh viện (HIS) giúp tối ưu hóa quy trình khám chữa bệnh và giảm thời gian chờ đợi của bệnh nhân.",
    date: "05/05/2024",
    image:
      "https://images.unsplash.com/photo-1516549655169-df83a0774514?q=80&w=800&auto=format&fit=crop",
    category: "digital",
  },
];

export const MOCK_INTERNATIONAL = [
  {
    id: "i1",
    title:
      "WHO cảnh báo biến chủng cúm mới: Việt Nam chủ động giám sát ngay từ cửa khẩu",
    date: "13/01/2026",
    image: "https://picsum.photos/seed/inter1/600/400",
  },
  {
    id: "i2",
    title:
      "Hợp tác y tế Việt - Nhật: Chuyển giao công nghệ phẫu thuật nội soi bằng Robot",
    date: "09/01/2026",
    image: "https://picsum.photos/seed/inter2/600/400",
  },
  {
    id: "i3",
    title:
      'Các nước ASEAN thống nhất cơ chế "Hộ chiếu vắc xin" điện tử phiên bản 2.0',
    date: "28/12/2025",
    image: "https://picsum.photos/seed/inter3/600/400",
  },
];
export const MOCK_CULTURE = [
  {
    id: "s1",
    title:
      "Giải bóng đá Cup Sức khỏe Thủ đô 2026: Bệnh viện Thanh Nhàn vô địch",
    date: "14/01/2026",
    image: "https://picsum.photos/seed/sport1/600/400",
  },
  {
    id: "s2",
    title: "Hội thao ngành Y tế: Hơn 2.000 vận động viên tham gia chạy việt dã",
    date: "08/01/2026",
    image: "https://picsum.photos/seed/sport2/600/400",
  },
  {
    id: "s3",
    title:
      'Phong trào rèn luyện sức khỏe "Mỗi người dân đi bộ 10.000 bước mỗi ngày"',
    date: "01/01/2026",
    image: "https://picsum.photos/seed/sport3/600/400",
  },
];
export const MOCK_SPORTS = [
  {
    id: "s1",
    title:
      "Giải bóng đá Cup Sức khỏe Thủ đô 2026: Bệnh viện Thanh Nhàn vô địch",
    date: "14/01/2026",
    image: "https://picsum.photos/seed/sport1/600/400",
  },
  {
    id: "s2",
    title: "Hội thao ngành Y tế: Hơn 2.000 vận động viên tham gia chạy việt dã",
    date: "08/01/2026",
    image: "https://picsum.photos/seed/sport2/600/400",
  },
  {
    id: "s3",
    title:
      'Phong trào rèn luyện sức khỏe "Mỗi người dân đi bộ 10.000 bước mỗi ngày"',
    date: "01/01/2026",
    image: "https://picsum.photos/seed/sport3/600/400",
  },
];

export const CATEGORIES = [
  {
    id: 3,
    title: "Khám bệnh - chữa bệnh",
    icon: Stethoscope,
    iconColor: "text-pink-600",
    hoverColor: "text-pink-600",
    image: "https://suckhoethudo.vn/assets/kham benh-__1wzyZ_.png",
    data: [],
  },
  {
    id: 4,
    title: "Phòng bệnh - Nâng cao sức khỏe",
    icon: ShieldPlus,
    iconColor: "text-orange-500",
    hoverColor: "text-orange-600",
    image: "https://suckhoethudo.vn/assets/phong benh-CTWuljBT.png",
    data: [],
    paddingClass: "md:pl-8",
  },
  {
    id: 5,
    title: "Bảo trợ xã hội",
    icon: HeartHandshake,
    iconColor: "text-blue-500",
    hoverColor: "text-blue-600",
    image: "https://suckhoethudo.vn/assets/bao tro XH-By5fco0o.png",
    data: [],
    paddingClass: "md:pl-8",
  },
  {
    id: 6,
    title: "Chuyển đổi số y tế",
    icon: Laptop2,
    iconColor: "text-pink-600",
    hoverColor: "text-pink-600",
    image: "https://suckhoethudo.vn/assets/chuyen doi so-DSivldkT.png",
    data: [],
  },
  {
    id: 7,
    title: "Chính sách y tế - Bảo hiểm y tế",
    icon: FileText,
    iconColor: "text-orange-500",
    hoverColor: "text-orange-600",
    image: "https://suckhoethudo.vn/assets/chinh sach y te-C_dDpJVZ.png",
    data: [],
    paddingClass: "md:pl-8",
  },
  {
    id: 8,
    title: "Gương người tốt - việc tốt",
    icon: Award,
    iconColor: "text-blue-500",
    hoverColor: "text-blue-600",
    image: "https://suckhoethudo.vn/assets/guong nguoi tot-C7NJJGDV.png",
    data: [],
    paddingClass: "md:pl-8",
  },
];

export const capcuu = [
  {
    id: "AMB-1",
    plateNumber: "29A-11501",
    status: "BUSY",
    coords: [20.937454983400016, 106.02177631564803],
    driver: "Nguyễn Văn 1",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 29,
  },
  {
    id: "AMB-2",
    plateNumber: "29A-11502",
    status: "AVAILABLE",
    coords: [21.154913132483184, 106.08395929366134],
    driver: "Nguyễn Văn 2",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 59,
  },
  {
    id: "AMB-3",
    plateNumber: "29A-11503",
    status: "BUSY",
    coords: [21.046831124410662, 105.86904576606071],
    driver: "Nguyễn Văn 3",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 28,
  },
  {
    id: "AMB-4",
    plateNumber: "29A-11504",
    status: "BUSY",
    coords: [20.93853320979846, 106.05014803137576],
    driver: "Nguyễn Văn 4",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 50,
  },
  {
    id: "AMB-5",
    plateNumber: "29A-11505",
    status: "BUSY",
    coords: [20.758911801242185, 105.85827428515537],
    driver: "Nguyễn Văn 5",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 10,
  },
  {
    id: "AMB-6",
    plateNumber: "29A-11506",
    status: "AVAILABLE",
    coords: [20.87148082950425, 105.74308047378393],
    driver: "Nguyễn Văn 6",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 14,
  },
  {
    id: "AMB-7",
    plateNumber: "29A-11507",
    status: "AVAILABLE",
    coords: [20.99552398176946, 106.01858697274885],
    driver: "Nguyễn Văn 7",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 39,
  },
  {
    id: "AMB-8",
    plateNumber: "29A-11508",
    status: "AVAILABLE",
    coords: [20.815570827039856, 106.02655007326038],
    driver: "Nguyễn Văn 8",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 55,
  },
  {
    id: "AMB-9",
    plateNumber: "29A-11509",
    status: "AVAILABLE",
    coords: [21.2, 105.64769929405757],
    driver: "Nguyễn Văn 9",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 6,
  },
  {
    id: "AMB-10",
    plateNumber: "29A-11510",
    status: "AVAILABLE",
    coords: [20.76009263986878, 105.70535710624523],
    driver: "Nguyễn Văn 10",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 2,
  },
  {
    id: "AMB-11",
    plateNumber: "29A-11511",
    status: "AVAILABLE",
    coords: [21.080175059924194, 105.80859028706544],
    driver: "Nguyễn Văn 11",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 32,
  },
  {
    id: "AMB-12",
    plateNumber: "29A-11512",
    status: "AVAILABLE",
    coords: [20.791037339659244, 105.53998533359352],
    driver: "Nguyễn Văn 12",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 34,
  },
  {
    id: "AMB-13",
    plateNumber: "29A-11513",
    status: "AVAILABLE",
    coords: [21.246835190405495, 106.00851810939294],
    driver: "Nguyễn Văn 13",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 59,
  },
  {
    id: "AMB-14",
    plateNumber: "29A-11514",
    status: "AVAILABLE",
    coords: [20.963657466120072, 105.77230802295252],
    driver: "Nguyễn Văn 14",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 24,
  },
  {
    id: "AMB-15",
    plateNumber: "29A-11515",
    status: "AVAILABLE",
    coords: [21.171868678349384, 105.67885812812402],
    driver: "Nguyễn Văn 15",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 19,
  },
  {
    id: "AMB-16",
    plateNumber: "29A-11516",
    status: "AVAILABLE",
    coords: [21.071268284175613, 105.95447632390395],
    driver: "Nguyễn Văn 16",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 0,
  },
  {
    id: "AMB-17",
    plateNumber: "29A-11517",
    status: "AVAILABLE",
    coords: [20.78307507291374, 105.96991731616716],
    driver: "Nguyễn Văn 17",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 5,
  },
  {
    id: "AMB-18",
    plateNumber: "29A-11518",
    status: "BUSY",
    coords: [20.880381095190945, 105.56754975657924],
    driver: "Nguyễn Văn 18",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 47,
  },
  {
    id: "AMB-19",
    plateNumber: "29A-11519",
    status: "AVAILABLE",
    coords: [21.195077958816036, 105.71006061509812],
    driver: "Nguyễn Văn 19",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 6,
  },
  {
    id: "AMB-20",
    plateNumber: "29A-11520",
    status: "AVAILABLE",
    coords: [21.189492275971716, 106.05403103902316],
    driver: "Nguyễn Văn 20",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 21,
  },
  {
    id: "AMB-21",
    plateNumber: "29A-11521",
    status: "BUSY",
    coords: [21.037854012275957, 105.86105398429736],
    driver: "Nguyễn Văn 21",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 13,
  },
  {
    id: "AMB-22",
    plateNumber: "29A-11522",
    status: "AVAILABLE",
    coords: [21.045085543843793, 105.70629603421747],
    driver: "Nguyễn Văn 22",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 36,
  },
  {
    id: "AMB-23",
    plateNumber: "29A-11523",
    status: "AVAILABLE",
    coords: [20.96743885147622, 105.73423944451774],
    driver: "Nguyễn Văn 23",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 53,
  },
  {
    id: "AMB-24",
    plateNumber: "29A-11524",
    status: "AVAILABLE",
    coords: [20.964516586993536, 105.78144977328971],
    driver: "Nguyễn Văn 24",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 12,
  },
  {
    id: "AMB-25",
    plateNumber: "29A-11525",
    status: "BUSY",
    coords: [21.01657476701269, 105.74837579196206],
    driver: "Nguyễn Văn 25",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 35,
  },
  {
    id: "AMB-26",
    plateNumber: "29A-11526",
    status: "BUSY",
    coords: [20.98436942987216, 105.71690338474781],
    driver: "Nguyễn Văn 26",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 25,
  },
  {
    id: "AMB-27",
    plateNumber: "29A-11527",
    status: "AVAILABLE",
    coords: [20.989050100706653, 105.84347845798487],
    driver: "Nguyễn Văn 27",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 20,
  },
  {
    id: "AMB-28",
    plateNumber: "29A-11528",
    status: "AVAILABLE",
    coords: [21.04, 105.83010628373606],
    driver: "Nguyễn Văn 28",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 22,
  },
  {
    id: "AMB-29",
    plateNumber: "29A-11529",
    status: "AVAILABLE",
    coords: [21.01126262604279, 105.82545172915869],
    driver: "Nguyễn Văn 29",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 39,
  },
  {
    id: "AMB-30",
    plateNumber: "29A-11530",
    status: "AVAILABLE",
    coords: [21.00982624625811, 105.80411614308493],
    driver: "Nguyễn Văn 30",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 25,
  },
  {
    id: "AMB-31",
    plateNumber: "29A-11531",
    status: "AVAILABLE",
    coords: [21.004476681016776, 105.86144422123242],
    driver: "Nguyễn Văn 31",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 9,
  },
  {
    id: "AMB-32",
    plateNumber: "29A-11532",
    status: "BUSY",
    coords: [20.966679657118306, 105.70420305816808],
    driver: "Nguyễn Văn 32",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 44,
  },
  {
    id: "AMB-33",
    plateNumber: "29A-11533",
    status: "BUSY",
    coords: [20.959651672694086, 105.87387477306335],
    driver: "Nguyễn Văn 33",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 6,
  },
  {
    id: "AMB-34",
    plateNumber: "29A-11534",
    status: "AVAILABLE",
    coords: [20.989249600510345, 105.71299372255368],
    driver: "Nguyễn Văn 34",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 16,
  },
  {
    id: "AMB-35",
    plateNumber: "29A-11535",
    status: "BUSY",
    coords: [20.969586324518925, 105.72333696571864],
    driver: "Nguyễn Văn 35",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 54,
  },
  {
    id: "AMB-36",
    plateNumber: "29A-11536",
    status: "AVAILABLE",
    coords: [21.014660202238257, 105.72716245332846],
    driver: "Nguyễn Văn 36",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 40,
  },
  {
    id: "AMB-37",
    plateNumber: "29A-11537",
    status: "AVAILABLE",
    coords: [21.006326794827785, 105.84320152152458],
    driver: "Nguyễn Văn 37",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 12,
  },
  {
    id: "AMB-38",
    plateNumber: "29A-11538",
    status: "AVAILABLE",
    coords: [20.995771498412548, 105.89116923122214],
    driver: "Nguyễn Văn 38",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 12,
  },
  {
    id: "AMB-39",
    plateNumber: "29A-11539",
    status: "AVAILABLE",
    coords: [20.96827025814269, 105.88021321740112],
    driver: "Nguyễn Văn 39",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 57,
  },
  {
    id: "AMB-40",
    plateNumber: "29A-11540",
    status: "AVAILABLE",
    coords: [21.016402865558703, 105.8533298027865],
    driver: "Nguyễn Văn 40",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 9,
  },
  {
    id: "AMB-41",
    plateNumber: "29A-11541",
    status: "BUSY",
    coords: [20.999504418535594, 105.73],
    driver: "Nguyễn Văn 41",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 35,
  },
  {
    id: "AMB-42",
    plateNumber: "29A-11542",
    status: "AVAILABLE",
    coords: [20.978512055522973, 105.82982545105583],
    driver: "Nguyễn Văn 42",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 6,
  },
  {
    id: "AMB-43",
    plateNumber: "29A-11543",
    status: "AVAILABLE",
    coords: [21.027654708174087, 105.71923328846272],
    driver: "Nguyễn Văn 43",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 36,
  },
  {
    id: "AMB-44",
    plateNumber: "29A-11544",
    status: "BUSY",
    coords: [20.970605568721133, 105.7245797045254],
    driver: "Nguyễn Văn 44",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 36,
  },
  {
    id: "AMB-45",
    plateNumber: "29A-11545",
    status: "AVAILABLE",
    coords: [21.02703924084159, 105.82689880071938],
    driver: "Nguyễn Văn 45",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 33,
  },
  {
    id: "AMB-46",
    plateNumber: "29A-11546",
    status: "AVAILABLE",
    coords: [20.95401980922146, 105.88678349785785],
    driver: "Nguyễn Văn 46",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 14,
  },
  {
    id: "AMB-47",
    plateNumber: "29A-11547",
    status: "AVAILABLE",
    coords: [20.954353377470373, 105.81258714882455],
    driver: "Nguyễn Văn 47",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 54,
  },
  {
    id: "AMB-48",
    plateNumber: "29A-11548",
    status: "AVAILABLE",
    coords: [20.972931408210123, 105.86043194559119],
    driver: "Nguyễn Văn 48",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 4,
  },
  {
    id: "AMB-49",
    plateNumber: "29A-11549",
    status: "BUSY",
    coords: [20.99615977103259, 105.79262418350127],
    driver: "Nguyễn Văn 49",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 2,
  },
  {
    id: "AMB-50",
    plateNumber: "29A-11550",
    status: "BUSY",
    coords: [20.97960837012413, 105.74213405171508],
    driver: "Nguyễn Văn 50",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 2,
  },
]; 

export const ALL_FACILITIES = [
  {
    id: "cc-atvstp-hn",
    name: "Chi cục An toàn vệ sinh thực phẩm Hà Nội",
    type: "CC",
    category: "Chi cục",
    address: "35 P. Trần Bình, Phường Mai Dịch, Thành phố Hà Nội",
    phone: "02437684024",
    coords: [21.0345, 105.7766],
    description: "Đơn vị quản lý nhà nước trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "cc-danso-treem",
    name: "Chi cục Dân số, Trẻ em và Phòng, chống tệ nạn xã hội",
    type: "CC",
    category: "Chi cục",
    address: "18 P. Sơn Tây, Phường Ba Đình, Thành phố Hà Nội",
    phone: "",
    coords: [21.0305, 105.829],
    description: "Đơn vị quản lý nhà nước trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-hadong",
    name: "Bệnh viện đa khoa Hà Đông",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 2 Bế Văn Đàn, Phường Hà Đông, Thành phố Hà Nội",
    phone: "02433824216",
    coords: [20.9715, 105.7735],
    description: "Bệnh viện đa khoa công lập trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-dongda",
    name: "Bệnh viện đa khoa Đống Đa",
    type: "BV",
    category: "Bệnh viện",
    address: "Ngõ 180 Nguyễn Lương Bằng, Phường Đống Đa, Thành phố Hà Nội",
    phone: "02438517140",
    coords: [21.0125, 105.8275],
    description: "Bệnh viện đa khoa công lập trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-bacthanglong",
    name: "Bệnh viện Bắc Thăng Long",
    type: "BV",
    category: "Bệnh viện",
    address: "Tổ 18, Thị trấn Đông Anh, Thành phố Hà Nội",
    phone: "02438832727",
    coords: [21.1448, 105.8427],
    description: "Bệnh viện đa khoa công lập trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-thanhtri",
    name: "Bệnh viện đa khoa Thanh Trì",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 1 Tứ Hiệp, Xã Thanh Trì, Thành phố Hà Nội",
    phone: "02422182170",
    // coords: [20.9485, 105.8467],
    coords: [20.9487,105.8437],
    description: "Bệnh viện đa khoa công lập trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-hoenhai",
    name: "Bệnh viện đa khoa Hòe Nhai",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 34 Hòe Nhai, Phường Ba Đình, Thành phố Hà Nội",
    phone: "02439272980",
    coords: [21.0410192,105.8448996],
    description: "Bệnh viện đa khoa công lập trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-donganh",
    name: "Bệnh viện đa khoa Đông Anh",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 1 Uy Nỗ, Xã Đông Anh, Thành phố Hà Nội",
    phone: "02438832450",
    coords: [21.1405, 105.8464],
    description: "Bệnh viện đa khoa công lập trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-vandinh",
    name: "Bệnh viện đa khoa Vân Đình",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 10 đường 22/8, Xã Vân Đình, Thành phố Hà Nội",
    phone: "02433882212",
    coords: [20.8354, 105.7651],
    description: "Bệnh viện đa khoa công lập trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-sontay",
    name: "Bệnh viện đa khoa Sơn Tây",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 304A Đường Lê Lợi, Phường Sơn Tây, Thành phố Hà Nội",
    phone: "0966401616",
    coords: [21.1398, 105.5015],
    description: "Bệnh viện đa khoa công lập trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-namthanglong",
    name: "Bệnh viện Nam Thăng Long",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 38 Tân Xuân, Phường Xuân Đỉnh, Thành phố Hà Nội",
    phone: "02438386009",
    coords: [21.085, 105.7865],
    description: "Bệnh viện đa khoa công lập trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-phusan-hn",
    name: "Bệnh viện Phụ sản Hà Nội",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 929 Đường La Thành, Phường Giảng Võ, Thành phố Hà Nội",
    phone: "02438343181",
    coords: [21.0261, 105.8118],
    description: "Bệnh viện chuyên khoa sản phụ khoa trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-1",
    name: "Bệnh viện đa khoa Xanh Pôn",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 12 Chu Văn An, Phường Ba Đình, Thành phố Hà Nội",
    phone: "02438233075",
    coords: [21.0318, 105.8396],
    description:
      "Bệnh viện đa khoa đầu ngành Ngoại khoa và Nhi khoa của Thủ đô.",
  },
  {
    id: "bv-2",
    name: "Bệnh viện Thanh Nhàn",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 42 Thanh Nhàn, Phường Hai Bà Trưng, Thành phố Hà Nội",
    phone: "02439714363",
    coords: [21.0028, 105.8569],
    description:
      "Bệnh viện đa khoa hạng I, mũi nhọn về Nội khoa và hồi sức cấp cứu.",
  },
  {
    id: "bv-3",
    name: "Bệnh viện đa khoa Đức Giang",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 54 Trường Lâm, Phường Long Biên, Thành phố Hà Nội",
    phone: "02438271515",
    coords: [21.0528, 105.8969],
    description: "Cơ sở y tế hạng I khu vực phía Đông thành phố.",
  },
  {
    id: "bv-h1",
    name: "Bệnh viện đa khoa Ba Vì",
    type: "BV",
    category: "Bệnh viện",
    address: "Thị trấn Tây Đằng, Xã Ba Vì, Thành phố Hà Nội",
    phone: "02433863144",
    coords: [21.2352, 105.4125],
    description: "Phục vụ khám chữa bệnh cho nhân dân Ba Vì.",
  },
  {
    id: "bv-nhi-hn",
    name: "Bệnh viện Nhi Hà Nội",
    type: "BV",
    category: "Bệnh viện",
    address: "Phố Nguyễn Trác, Phường Yên Nghĩa, Thành phố Hà Nội",
    phone: "0826722822",
    coords: [20.9431, 105.7535],
    description: "Bệnh viện chuyên khoa nhi trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-mat-hn",
    name: "Bệnh viện Mắt Hà Nội",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 37 Hai Bà Trưng, Phường Cửa Nam, Thành phố Hà Nội",
    phone: "0848958866",
    coords: [21.0255, 105.8495],
    description: "Bệnh viện chuyên khoa mắt trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-tamthan-hn",
    name: "Bệnh viện Tâm thần Hà Nội",
    type: "BV",
    category: "Bệnh viện",
    address: "Ngõ 467 Nguyễn Văn Linh, Phường Long Biên, Thành phố Hà Nội",
    phone: "02438276534",
    coords: [21.0345, 105.895],
    description: "Bệnh viện chuyên khoa tâm thần (Trụ sở chính Sài Đồng)",
  },
  {
    id: "bv-dk-yhct-hn",
    name: "Bệnh viện đa khoa Y học cổ truyền Hà Nội",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 8 Phạm Hùng, Phường Mai Dịch, Thành phố Hà Nội",
    phone: "02437684059",
    coords: [21.0305, 105.783],
    description: "Bệnh viện y học cổ truyền trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-vn-cuba",
    name: "Bệnh viện Hữu nghị Việt Nam - Cu Ba",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 37 Hai Bà Trưng, Phường Cửa Nam, Thành phố Hà Nội",
    phone: "0967671616",
    coords: [21.0255, 105.8475],
    description: "Bệnh viện đa khoa chuyên khoa Răng Hàm Mặt, Tai Mũi Họng",
  },
  {
    id: "bv-phoi-hn",
    name: "Bệnh viện Phổi Hà Nội",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 44 Thanh Nhàn, Phường Hai Bà Trưng, Thành phố Hà Nội",
    phone: "0904599583",
    coords: [21.002, 105.8585],
    description: "Bệnh viện chuyên khoa phổi trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-ungbuou-hn",
    name: "Bệnh viện Ung bướu Hà Nội",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 42A Thanh Nhàn, Phường Hai Bà Trưng, Thành phố Hà Nội",
    phone: "0915546116",
    coords: [21.0025, 105.858],
    description: "Bệnh viện chuyên khoa ung bướu trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-tim-hn",
    name: "Bệnh viện Tim Hà Nội",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 92 Trần Hưng Đạo, Phường Cửa Nam, Thành phố Hà Nội",
    phone: "02439427791",
    coords: [21.0225, 105.8455],
    description: "Bệnh viện chuyên khoa tim mạch trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-dalieuhn",
    name: "Bệnh viện Da liễu Hà Nội",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 79B Nguyễn Khuyến, Phường Đống Đa, Thành phố Hà Nội",
    phone: "19008186",
    coords: [21.0285, 105.836],
    description: "Bệnh viện chuyên khoa da liễu trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-yhct-hadong",
    name: "Bệnh viện Y học cổ truyền Hà Đông",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 23 Nguyễn Lương Bằng, Phường Hà Đông, Thành phố Hà Nội",
    phone: "02433598363",
    coords: [20.9739, 105.7782],
    description: "Bệnh viện y học cổ truyền trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-tamthan-myduc",
    name: "Bệnh viện Tâm thần Mỹ Đức",
    type: "BV",
    category: "Bệnh viện",
    address: "Xã Lê Thanh, Xã Mỹ Đức, Thành phố Hà Nội",
    phone: "02433847226",
    coords: [20.7166, 105.7365],
    description: "Bệnh viện tâm thần chuyên khoa khu vực",
  },
  {
    id: "bv-than-hn",
    name: "Bệnh viện Thận Hà Nội",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 70 Nguyễn Chí Thanh, Phường Đống Đa, Thành phố Hà Nội",
    phone: "02437757194",
    coords: [21.0232, 105.8105],
    description: "Bệnh viện chuyên khoa thận - tiết niệu",
  },
  {
    id: "bv-09",
    name: "Bệnh viện 09",
    type: "BV",
    category: "Bệnh viện",
    address: "Phố Tân Mai, Phường Tân Mai, Thành phố Hà Nội",
    phone: "02438641261",
    coords: [20.9856, 105.8485],
    description: "Bệnh viện chuyên khoa truyền nhiễm và điều trị HIV/AIDS",
  },
  {
    id: "bv-phcn",
    name: "Bệnh viện Phục hồi chức năng",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 35 Lê Văn Thiêm, Phường Giảng Võ, Thành phố Hà Nội",
    phone: "02432216229",
    coords: [20.9985, 105.802],
    description: "Bệnh viện chuyên khoa phục hồi chức năng",
  },
  {
    id: "bv-maihuong",
    name: "Bệnh viện Tâm thần Ban ngày Mai Hương",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 4 Hồng Mai, Phường Hai Bà Trưng, Thành phố Hà Nội",
    phone: "02436275762",
    coords: [21.0045, 105.8525],
    description: "Bệnh viện tâm thần điều trị ban ngày",
  },
  {
    id: "bv-dk-socson",
    name: "Bệnh viện đa khoa Sóc Sơn",
    type: "BV",
    category: "Bệnh viện",
    address: "Thị trấn Sóc Sơn, Xã Sóc Sơn, Thành phố Hà Nội",
    phone: "02435953784",
    coords: [21.2597, 105.8481],
    description: "Bệnh viện đa khoa hạng II tuyến huyện",
  },
  {
    id: "bv-dk-gialam",
    name: "Bệnh viện đa khoa huyện Gia Lâm",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 135 Tố Hữu, Xã Gia Lâm, Thành phố Hà Nội",
    phone: "",
    coords: [21.0185, 105.9375],
    description: "Bệnh viện đa khoa hạng II tuyến huyện",
  },
  {
    id: "bv-dk-bavi",
    name: "Bệnh viện đa khoa huyện Ba Vì",
    type: "BV",
    category: "Bệnh viện",
    address: "Xã Chu Minh, Xã Ba Vì, Thành phố Hà Nội",
    phone: "02433863144",
    coords: [21.1869, 105.4238],
    description: "Bệnh viện đa khoa hạng II tuyến huyện",
  },
  {
    id: "bv-dk-thachthat",
    name: "Bệnh viện đa khoa huyện Thạch Thất",
    type: "BV",
    category: "Bệnh viện",
    address: "Xã Kim Quan, Xã Thạch Thất, Thành phố Hà Nội",
    phone: "02433842235",
    coords: [21.0604, 105.5757],
    description: "Bệnh viện đa khoa hạng II tuyến huyện",
  },
  {
    id: "bv-dk-quochoai",
    name: "Bệnh viện đa khoa huyện Quốc Oai",
    type: "BV",
    category: "Bệnh viện",
    address: "Thị trấn Quốc Oai, Xã Quốc Oai, Thành phố Hà Nội",
    phone: "02433843144",
    coords: [21.0382, 105.6409],
    description: "Bệnh viện đa khoa hạng II tuyến huyện",
  },
  {
    id: "bv-dk-danphuong",
    name: "Bệnh viện đa khoa huyện Đan Phượng",
    type: "BV",
    category: "Bệnh viện",
    address: "Thị trấn Phùng, Xã Đan Phượng, Thành phố Hà Nội",
    phone: "02433886223",
    coords: [21.0856, 105.6822],
    description: "Bệnh viện đa khoa hạng II tuyến huyện",
  },
  {
    id: "bv-dk-hoaideuc",
    name: "Bệnh viện đa khoa huyện Hoài Đức",
    type: "BV",
    category: "Bệnh viện",
    address: "Thôn Lũng Kênh, Xã Hoài Đức, Thành phố Hà Nội",
    phone: "02433861224",
    coords: [21.0407, 105.7158],
    description: "Bệnh viện đa khoa hạng II tuyến huyện",
  },
  {
    id: "bv-dk-chuongmy",
    name: "Bệnh viện đa khoa huyện Chương Mỹ",
    type: "BV",
    category: "Bệnh viện",
    address: "Thị trấn Chúc Sơn, Phường Chương Mỹ, Thành phố Hà Nội",
    phone: "02433866124",
    coords: [20.8675, 105.6744],
    description: "Bệnh viện đa khoa hạng II tuyến huyện",
  },
  {
    id: "bv-dk-thanhoai",
    name: "Bệnh viện đa khoa huyện Thanh Oai",
    type: "BV",
    category: "Bệnh viện",
    address: "Thị trấn Kim Bài, Xã Thanh Oai, Thành phố Hà Nội",
    phone: "02433873124",
    coords: [20.8526, 105.7728],
    description: "Bệnh viện đa khoa hạng II tuyến huyện",
  },
  {
    id: "bv-dk-myduc",
    name: "Bệnh viện đa khoa huyện Mỹ Đức",
    type: "BV",
    category: "Bệnh viện",
    address: "Thị trấn Đại Nghĩa, Xã Mỹ Đức, Thành phố Hà Nội",
    phone: "02433847226",
    coords: [20.7139, 105.7378],
    description: "Bệnh viện đa khoa hạng II tuyến huyện",
  },
  {
    id: "bv-dk-thuongtin",
    name: "Bệnh viện đa khoa huyện Thường Tín",
    type: "BV",
    category: "Bệnh viện",
    address: "Thị trấn Thường Tín, Xã Thường Tín, Thành phố Hà Nội",
    phone: "02433852224",
    coords: [20.8736, 105.8699],
    description: "Bệnh viện đa khoa hạng II tuyến huyện",
  },
  {
    id: "bv-dk-phuxuyen",
    name: "Bệnh viện đa khoa huyện Phú Xuyên",
    type: "BV",
    category: "Bệnh viện",
    address: "Thị trấn Phú Xuyên, Xã Phú Xuyên, Thành phố Hà Nội",
    phone: "02433854224",
    coords: [20.7408, 105.9146],
    description: "Bệnh viện đa khoa hạng II tuyến huyện",
  },
  {
    id: "bv-dk-melinh",
    name: "Bệnh viện đa khoa huyện Mê Linh",
    type: "BV",
    category: "Bệnh viện",
    address: "Xã Mê Linh, Thành phố Hà Nội",
    phone: "02438161224",
    coords: [21.1803, 105.7119],
    description: "Bệnh viện đa khoa hạng II tuyến huyện",
  },
  {
    id: "bv-dk-phuctho",
    name: "Bệnh viện đa khoa huyện Phúc Thọ",
    type: "BV",
    category: "Bệnh viện",
    address: "Thị trấn Phúc Thọ, Xã Phúc Thọ, Thành phố Hà Nội",
    phone: "02433843224",
    coords: [21.1139, 105.5617],
    description: "Bệnh viện đa khoa hạng II tuyến huyện",
  },
  {
    id: "tt-1",
    name: "Trung tâm Kiểm soát bệnh tật (CDC) Hà Nội",
    type: "TT",
    category: "Trung tâm chuyên khoa",
    address: "Số 70 Nguyễn Chí Thanh, Phường Đống Đa, Thành phố Hà Nội",
    phone: "02438343520",
    coords: [21.0232, 105.8105],
    description: "Đơn vị đầu ngành về y tế dự phòng và kiểm soát dịch bệnh.",
  },
  {
    id: "bt-1",
    name: "Làng trẻ em SOS Hà Nội",
    type: "BT",
    category: "Cơ sở bảo trợ",
    address: "Số 2 Doãn Kế Thiện, Phường Mai Dịch, Thành phố Hà Nội",
    phone: "02437644022",
    coords: [21.0385, 105.7812],
    description: "Nuôi dưỡng và chăm sóc trẻ em mồ côi, có hoàn cảnh đặc biệt.",
  },
  {
    id: "bt-115-hn",
    name: "Trung tâm Cấp cứu 115 Hà Nội",
    type: "TT",
    category: "Trung tâm",
    address: "Số 11 Phan Chu Trinh, Phường Cửa Nam, Thành phố Hà Nội",
    phone: "02438255612",
    coords: [21.0238, 105.8572],
    description: "Trung tâm cấp cứu ngoại viện của thành phố Hà Nội",
  },
  {
    id: "bt-cdc-hn",
    name: "Trung tâm Kiểm soát bệnh tật thành phố Hà Nội",
    type: "TT",
    category: "Trung tâm",
    address: "Số 70 Nguyễn Chí Thanh, Phường Đống Đa, Thành phố Hà Nội",
    phone: "02438343537",
    coords: [21.0232, 105.8105],
    description:
      "Trung tâm kiểm soát và phòng chống dịch bệnh của thành phố Hà Nội",
  },
  {
    id: "bt-kiemnghiem-hn",
    name: "Trung tâm Kiểm nghiệm thuốc, mỹ phẩm, thực phẩm Hà Nội",
    type: "TT",
    category: "Trung tâm",
    address: "Số 7 ngõ 107 Nguyễn Chí Thanh, Phường Đống Đa, Thành phố Hà Nội",
    phone: "02437737603",
    coords: [21.0245, 105.808],
    description: "Trung tâm kiểm nghiệm thuốc, mỹ phẩm và thực phẩm",
  },
  {
    id: "bt-giamdinhy-hn",
    name: "Trung tâm Giám định y khoa Hà Nội",
    type: "TT",
    category: "Trung tâm",
    address: "Số 35 Trần Bình, Phường Mai Dịch, Thành phố Hà Nội",
    phone: "02437684024",
    coords: [21.0345, 105.7766],
    description: "Trung tâm giám định y khoa trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bt-phapy-hn",
    name: "Trung tâm Pháp y Hà Nội",
    type: "TT",
    category: "Trung tâm",
    address: "Số 35 Trần Bình, Phường Mai Dịch, Thành phố Hà Nội",
    phone: "02437684024",
    coords: [21.0345, 105.7766],
    description: "Trung tâm pháp y phục vụ công tác giám định tư pháp",
  },
  {
    id: "bt-btxh-1",
    name: "Trung tâm Bảo trợ xã hội 1 Hà Nội",
    type: "BT",
    category: "Trung tâm",
    address: "Xã Chu Minh, Xã Ba Vì, Thành phố Hà Nội",
    phone: "02433863144",
    coords: [21.1769, 105.4126],
    description: "Trung tâm bảo trợ xã hội trực thuộc thành phố Hà Nội",
  },
  {
    id: "bt-btxh-2",
    name: "Trung tâm Bảo trợ xã hội 2 Hà Nội",
    type: "BT",
    category: "Trung tâm",
    address: "Thị trấn Vân Đình, Xã Vân Đình, Thành phố Hà Nội",
    phone: "02433882212",
    coords: [20.8612, 105.7639],
    description: "Trung tâm bảo trợ xã hội trực thuộc thành phố Hà Nội",
  },
  {
    id: "bt-btxh-3",
    name: "Trung tâm Bảo trợ xã hội 3 Hà Nội",
    type: "BT",
    category: "Trung tâm",
    address: "Thị trấn Sóc Sơn, Xã Sóc Sơn, Thành phố Hà Nội",
    phone: "02438841210",
    coords: [21.2587, 105.8461],
    description: "Trung tâm bảo trợ xã hội trực thuộc thành phố Hà Nội",
  },
  {
    id: "bt-tttt-1",
    name: "Trung tâm Chăm sóc và Phục hồi chức năng người tâm thần số 1 Hà Nội",
    type: "BT",
    category: "Trung tâm",
    address: "Xã Hòa Bình, Xã Thường Tín, Thành phố Hà Nội",
    phone: "02433852224",
    coords: [20.8789, 105.8513],
    description: "Trung tâm chăm sóc và phục hồi chức năng người tâm thần",
  },
  {
    id: "bt-tttt-2",
    name: "Trung tâm Chăm sóc và Phục hồi chức năng người tâm thần số 2 Hà Nội",
    type: "BT",
    category: "Trung tâm",
    address: "Xã Thụy An, Xã Ba Vì, Thành phố Hà Nội",
    phone: "02433863144",
    coords: [21.1489, 105.4204],
    description: "Trung tâm chăm sóc và phục hồi chức năng người tâm thần",
  },
  {
    id: "bt-khuyettat",
    name: "Trung tâm Chăm sóc người khuyết tật Hà Nội",
    type: "BT",
    category: "Trung tâm",
    address: "Thị trấn Chúc Sơn, Phường Chương Mỹ, Thành phố Hà Nội",
    phone: "02433866124",
    coords: [20.8726, 105.6732],
    description: "Trung tâm chăm sóc và hỗ trợ người khuyết tật",
  },
  {
    id: "bt-viet-han",
    name: "Trung tâm Phục hồi chức năng Việt - Hàn",
    type: "BT",
    category: "Trung tâm",
    address: "Số 23 Nguyễn Lương Bằng, Phường Hà Đông, Thành phố Hà Nội",
    phone: "02433824586",
    coords: [20.9719, 105.7796],
    description: "Trung tâm phục hồi chức năng hợp tác Việt – Hàn",
  },
  {
    id: "bt-birla",
    name: "Làng Trẻ em Birla Hà Nội",
    type: "BT",
    category: "Trung tâm",
    address: "Xã Chu Minh, Xã Ba Vì, Thành phố Hà Nội",
    phone: "02433863144",
    coords: [21.1824, 105.4068],
    description: "Cơ sở nuôi dưỡng và chăm sóc trẻ em có hoàn cảnh đặc biệt",
  },
  {
    id: "bt-tre-khuyettat",
    name: "Trung tâm Nuôi dưỡng trẻ khuyết tật Hà Nội",
    type: "BT",
    category: "Trung tâm",
    address: "Thị trấn Chúc Sơn, Phường Chương Mỹ, Thành phố Hà Nội",
    phone: "02433866124",
    coords: [20.8659, 105.6708],
    description: "Trung tâm nuôi dưỡng và chăm sóc trẻ khuyết tật",
  },
  {
    id: "bt-ctxh-treem",
    name: "Trung tâm Công tác xã hội và Quỹ Bảo trợ trẻ em Hà Nội",
    type: "BT",
    category: "Trung tâm",
    address: "Số 45 Bà Triệu, Phường Hà Đông, Thành phố Hà Nội",
    phone: "02432233111",
    coords: [20.9695, 105.7745],
    description: "Trung tâm công tác xã hội và bảo trợ trẻ em",
  },

  // Trạm y tế xã, phường =====================================================================================================================

  {
    id: "tyt-an-khanh",
    name: "Trạm y tế xã An Khánh",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã An Khánh, Thành phố Hà Nội",
    phone: "02433650432",
    coords: [21.0061, 105.7175],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-ba-dinh",
    name: "Trạm y tế phường Ba Đình",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Ba Đình, Thành phố Hà Nội",
    phone: "",
    coords: [21.1342, 105.5012],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-ba-vi",
    name: "Trạm y tế xã Ba Vì",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Ba Vì, Thành phố Hà Nội",
    phone: "",
    coords: [21.0612, 105.3854],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-bach-mai",
    name: "Trạm y tế phường Bạch Mai",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Bạch Mai, Thành phố Hà Nội",
    phone: "02438631124",
    coords: [21.0012, 105.8521],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-bat-bat",
    name: "Trạm y tế xã Bất Bạt",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Bất Bạt, Thành phố Hà Nội",
    phone: "",
    coords: [21.1965, 105.3524],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-bat-trang",
    name: "Trạm y tế xã Bát Tràng",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Bát Tràng, Thành phố Hà Nội",
    phone: "02438740333",
    coords: [20.9762, 105.9145],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-binh-minh",
    name: "Trạm y tế xã Bình Minh",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Bình Minh, Thành phố Hà Nội",
    phone: "",
    coords: [20.8954, 105.7951],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-bo-de",
    name: "Trạm y tế phường Bồ Đề",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Bồ Đề, Thành phố Hà Nội",
    phone: "02438723448",
    coords: [21.0342, 105.8775],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-cau-giay",
    name: "Trạm y tế phường Cầu Giấy",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Cầu Giấy, Thành phố Hà Nội",
    phone: "",
    coords: [21.0355, 105.7924],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-chuong-duong",
    name: "Trạm y tế xã Chương Dương",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Chương Dương, Thành phố Hà Nội",
    phone: "",
    coords: [20.8932, 105.8821],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-chuong-my",
    name: "Trạm y tế phường Chương Mỹ",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Chương Mỹ, Thành phố Hà Nội",
    phone: "",
    coords: [20.8715, 105.6742],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-chuyen-my",
    name: "Trạm y tế xã Chuyên Mỹ",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Chuyên Mỹ, Thành phố Hà Nội",
    phone: "",
    coords: [20.7354, 105.8421],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-co-do",
    name: "Trạm y tế xã Cổ Đô",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Cổ Đô, Thành phố Hà Nội",
    phone: "",
    coords: [21.2385, 105.3921],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-cua-nam",
    name: "Trạm y tế phường Cửa Nam",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Cửa Nam, Thành phố Hà Nội",
    phone: "",
    coords: [21.0275, 105.8415],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-da-phuc",
    name: "Trạm y tế xã Đa Phúc",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Đa Phúc, Thành phố Hà Nội",
    phone: "",
    coords: [20.9452, 105.6541],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-dai-mo",
    name: "Trạm y tế phường Đại Mỗ",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Đại Mỗ, Thành phố Hà Nội",
    phone: "",
    coords: [20.9982, 105.7551],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-dai-thanh",
    name: "Trạm y tế xã Đại Thành",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Đại Thành, Thành phố Hà Nội",
    phone: "",
    coords: [20.9412, 105.7145],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-dai-xuyen",
    name: "Trạm y tế xã Đại Xuyên",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Đại Xuyên, Thành phố Hà Nội",
    phone: "",
    coords: [20.7012, 105.8824],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-dan-hoa",
    name: "Trạm y tế xã Dân Hòa",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Dân Hòa, Thành phố Hà Nội",
    phone: "",
    coords: [20.8415, 105.7724],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-dan-phuong",
    name: "Trạm y tế xã Đan Phượng",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Đan Phượng, Thành phố Hà Nội",
    phone: "",
    coords: [21.0842, 105.6841],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-dinh-cong",
    name: "Trạm y tế phường Định Công",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Định Công, Thành phố Hà Nội",
    phone: "02438551374",
    coords: [20.9852, 105.8241],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-doai-phuong",
    name: "Trạm y tế xã Đoài Phương",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Đoài Phương, Thành phố Hà Nội",
    phone: "",
    coords: [21.2412, 105.8221],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-dong-anh",
    name: "Trạm y tế xã Đông Anh",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Đông Anh, Thành phố Hà Nội",
    phone: "",
    coords: [21.1415, 105.8424],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-dong-da",
    name: "Trạm y tế phường Đống Đa",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Đống Đa, Thành phố Hà Nội",
    phone: "",
    coords: [21.0115, 105.8251],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-dong-ngac",
    name: "Trạm y tế phường Đông Ngạc",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Đông Ngạc, Thành phố Hà Nội",
    phone: "",
    coords: [21.0892, 105.7824],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-duong-hoa",
    name: "Trạm y tế xã Dương Hòa",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Dương Hòa, Thành phố Hà Nội",
    phone: "",
    coords: [21.2212, 105.8521],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-duong-noi",
    name: "Trạm y tế phường Dương Nội",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Dương Nội, Thành phố Hà Nội",
    phone: "02433580212",
    coords: [20.9842, 105.7451],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-gia-lam",
    name: "Trạm y tế xã Gia Lâm",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Gia Lâm, Thành phố Hà Nội",
    phone: "",
    coords: [21.0242, 105.9324],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-giang-vo",
    name: "Trạm y tế phường Giảng Võ",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Giảng Võ, Thành phố Hà Nội",
    phone: "",
    coords: [21.0275, 105.8212],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-ha-bang",
    name: "Trạm y tế xã Hạ Bằng",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Hạ Bằng, Thành phố Hà Nội",
    phone: "",
    coords: [21.0142, 105.5421],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-ha-dong",
    name: "Trạm y tế phường Hà Đông",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Hà Đông, Thành phố Hà Nội",
    phone: "",
    coords: [20.9712, 105.7724],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-hai-ba-trung",
    name: "Trạm y tế phường Hai Bà Trưng",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Hai Bà Trưng, Thành phố Hà Nội",
    phone: "",
    coords: [21.0115, 105.8541],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-hat-mon",
    name: "Trạm y tế xã Hát Môn",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Hát Môn, Thành phố Hà Nội",
    phone: "",
    coords: [21.1442, 105.5851],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-hoa-lac",
    name: "Trạm y tế xã Hòa Lạc",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Hòa Lạc, Thành phố Hà Nội",
    phone: "",
    coords: [20.9842, 105.5324],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-hoa-phu",
    name: "Trạm y tế xã Hòa Phú",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Hòa Phú, Thành phố Hà Nội",
    phone: "",
    coords: [20.8542, 105.6221],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-hoa-xa",
    name: "Trạm y tế xã Hòa Xá",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Hòa Xá, Thành phố Hà Nội",
    phone: "",
    coords: [20.8042, 105.7824],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-hoai-duc",
    name: "Trạm y tế xã Hoài Đức",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Hoài Đức, Thành phố Hà Nội",
    phone: "",
    coords: [21.0342, 105.7121],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-hoan-kiem",
    name: "Trạm y tế phường Hoàn Kiếm",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Hoàn Kiếm, Thành phố Hà Nội",
    phone: "",
    coords: [21.0272, 105.8541],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-hoang-liet",
    name: "Trạm y tế phường Hoàng Liệt",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Hoàng Liệt, Thành phố Hà Nội",
    phone: "",
    coords: [20.9642, 105.8324],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-hoang-mai",
    name: "Trạm y tế phường Hoàng Mai",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Hoàng Mai, Thành phố Hà Nội",
    phone: "",
    coords: [20.9842, 105.8512],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-hong-ha",
    name: "Trạm y tế phường Hồng Hà",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Hồng Hà, Thành phố Hà Nội",
    phone: "",
    coords: [21.1112, 105.6521],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-hong-son",
    name: "Trạm y tế xã Hồng Sơn",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Hồng Sơn, Thành phố Hà Nội",
    phone: "",
    coords: [20.7842, 105.7524],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-hong-van",
    name: "Trạm y tế xã Hồng Vân",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Hồng Vân, Thành phố Hà Nội",
    phone: "",
    coords: [20.8642, 105.8921],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-hung-dao",
    name: "Trạm y tế xã Hưng Đạo",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Hưng Đạo, Thành phố Hà Nội",
    phone: "",
    coords: [21.2542, 105.9021],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-huong-son",
    name: "Trạm y tế xã Hương Sơn",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Hương Sơn, Thành phố Hà Nội",
    phone: "",
    coords: [20.6242, 105.7524],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-khuong-dinh",
    name: "Trạm y tế phường Khương Đình",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Khương Đình, Thành phố Hà Nội",
    phone: "",
    coords: [20.9872, 105.8171],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-kien-hung",
    name: "Trạm y tế phường Kiến Hưng",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Kiến Hưng, Thành phố Hà Nội",
    phone: "",
    coords: [20.9542, 105.7851],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-kieu-phu",
    name: "Trạm y tế xã Kiều Phú",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Kiều Phú, Thành phố Hà Nội",
    phone: "",
    coords: [21.0242, 105.6121],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-kim-anh",
    name: "Trạm y tế xã Kim Anh",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Kim Anh, Thành phố Hà Nội",
    phone: "",
    coords: [21.2342, 105.8121],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-kim-lien",
    name: "Trạm y tế phường Kim Liên",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 15 Lương Định Của, Phường Kim Liên, Thành phố Hà Nội",
    phone: "02438523122",
    coords: [21.0072, 105.8341],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-lang",
    name: "Trạm y tế phường Láng",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Láng, Thành phố Hà Nội",
    phone: "",
    coords: [21.0142, 105.8112],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-lien-minh",
    name: "Trạm y tế xã Liên Minh",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Liên Minh, Thành phố Hà Nội",
    phone: "",
    coords: [20.7642, 105.8724],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-linh-nam",
    name: "Trạm y tế phường Linh Nam",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Linh Nam, Thành phố Hà Nội",
    phone: "",
    coords: [20.9772, 105.8824],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-long-bien",
    name: "Trạm y tế phường Long Biên",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Long Biên, Thành phố Hà Nội",
    phone: "",
    coords: [21.0242, 105.8812],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-me-linh",
    name: "Trạm y tế xã Mê Linh",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Mê Linh, Thành phố Hà Nội",
    phone: "",
    coords: [21.1642, 105.7412],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-minh-chau",
    name: "Trạm y tế xã Minh Châu",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Minh Châu, Thành phố Hà Nội",
    phone: "",
    coords: [21.2242, 105.5141],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-my-duc",
    name: "Trạm y tế xã Mỹ Đức",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Mỹ Đức, Thành phố Hà Nội",
    phone: "",
    coords: [20.7142, 105.7371],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-nam-phu",
    name: "Trạm y tế xã Nam Phù",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Nam Phù, Thành phố Hà Nội",
    phone: "",
    coords: [20.6542, 105.8624],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-nghia-do",
    name: "Trạm y tế phường Nghĩa Đô",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Nghĩa Đô, Thành phố Hà Nội",
    phone: "",
    coords: [21.0442, 105.8041],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-ngoc-ha",
    name: "Trạm y tế phường Ngọc Hà",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Ngọc Hà, Thành phố Hà Nội",
    phone: "",
    coords: [21.0355, 105.8272],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-ngoc-hoi",
    name: "Trạm y tế xã Ngọc Hồi",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Ngọc Hồi, Thành phố Hà Nội",
    phone: "",
    coords: [20.9142, 105.8441],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-noi-bai",
    name: "Trạm y tế xã Nội Bài (Thanh Xuân)",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Thôn Thạch Lỗi, Xã Thanh Xuân, Thành phố Hà Nội",
    phone: "02438840303",
    coords: [21.2173238, 105.7707819],
    description:
      "Cơ sở y tế tuyến xã phục vụ nhân dân khu vực Thạch Lỗi và lân cận sân bay Nội Bài",
  },
  {
    id: "tyt-o-cho-dua",
    name: "Trạm y tế phường Ô Chợ Dừa",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Ô Chợ Dừa, Thành phố Hà Nội",
    phone: "",
    coords: [21.0212, 105.8241],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-o-dien",
    name: "Trạm y tế xã Ô Diên",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Ô Diên, Thành phố Hà Nội",
    phone: "",
    coords: [21.0942, 105.6541],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-phu-cat",
    name: "Trạm y tế xã Phú Cát",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Phú Cát, Thành phố Hà Nội",
    phone: "",
    coords: [20.9542, 105.5741],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-phu-dien",
    name: "Trạm y tế phường Phú Diễn",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Phú Diễn, Thành phố Hà Nội",
    phone: "02437638527",
    coords: [21.0442, 105.7641],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-phu-dong",
    name: "Trạm y tế xã Phù Đổng",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Phù Đổng, Thành phố Hà Nội",
    phone: "",
    coords: [21.0542, 105.9541],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-phu-luong",
    name: "Trạm y tế phường Phú Lương",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Phú Lương, Thành phố Hà Nội",
    phone: "",
    coords: [20.9342, 105.7641],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-phu-nghia",
    name: "Trạm y tế xã Phú Nghĩa",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Phú Nghĩa, Thành phố Hà Nội",
    phone: "",
    coords: [20.9042, 105.6241],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-phu-thuong",
    name: "Trạm y tế phường Phú Thượng",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Phú Thượng, Thành phố Hà Nội",
    phone: "",
    coords: [21.0842, 105.8141],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-phu-xuyen",
    name: "Trạm y tế xã Phú Xuyên",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Phú Xuyên, Thành phố Hà Nội",
    phone: "",
    coords: [20.7412, 105.9112],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-phuc-loc",
    name: "Trạm y tế xã Phúc Lộc",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Phúc Lộc, Thành phố Hà Nội",
    phone: "",
    coords: [21.1242, 105.5741],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-phuc-loi",
    name: "Trạm y tế phường Phúc Lợi",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Phúc Lợi, Thành phố Hà Nội",
    phone: "02438768114",
    coords: [21.0342, 105.9241],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-phuc-son",
    name: "Trạm y tế xã Phúc Sơn",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Phúc Sơn, Thành phố Hà Nội",
    phone: "",
    coords: [20.7542, 105.8141],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-phuc-thinh",
    name: "Trạm y tế xã Phúc Thịnh",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Phúc Thịnh, Thành phố Hà Nội",
    phone: "",
    coords: [21.1442, 105.5141],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-phuc-tho",
    name: "Trạm y tế xã Phúc Thọ",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Phúc Thọ, Thành phố Hà Nội",
    phone: "02433843224",
    coords: [21.1142, 105.5612],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-phuong-duc",
    name: "Trạm y tế xã Phượng Dực",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Phượng Dực, Thành phố Hà Nội",
    phone: "",
    coords: [20.7642, 105.8541],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-phuong-liet",
    name: "Trạm y tế phường Phương Liệt",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Phương Liệt, Thành phố Hà Nội",
    phone: "",
    coords: [20.9942, 105.8412],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-quang-bi",
    name: "Trạm y tế xã Quảng Bị",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Quảng Bị, Thành phố Hà Nội",
    phone: "",
    coords: [20.8442, 105.6541],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-quang-minh",
    name: "Trạm y tế xã Quang Minh",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Quang Minh, Thành phố Hà Nội",
    phone: "",
    coords: [21.1842, 105.7841],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-quang-oai",
    name: "Trạm y tế xã Quảng Oai",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Quảng Oai, Thành phố Hà Nội",
    phone: "",
    coords: [21.2442, 105.4241],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-quoc-oai",
    name: "Trạm y tế xã Quốc Oai",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Quốc Oai, Thành phố Hà Nội",
    phone: "",
    coords: [21.0342, 105.6412],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-soc-son",
    name: "Trạm y tế xã Sóc Sơn",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Sóc Sơn, Thành phố Hà Nội",
    phone: "",
    coords: [21.2642, 105.8471],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-son-dong",
    name: "Trạm y tế xã Sơn Đồng",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Sơn Đồng, Thành phố Hà Nội",
    phone: "",
    coords: [21.0242, 105.7041],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-son-tay",
    name: "Trạm y tế phường Sơn Tây",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Sơn Tây, Thành phố Hà Nội",
    phone: "",
    coords: [21.1342, 105.5012],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-suoi-hai",
    name: "Trạm y tế xã Suối Hai",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Suối Hai, Thành phố Hà Nội",
    phone: "",
    coords: [21.1842, 105.3841],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-tam-hung",
    name: "Trạm y tế xã Tam Hưng",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Tam Hưng, Thành phố Hà Nội",
    phone: "",
    coords: [20.8842, 105.8141],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-tay-ho",
    name: "Trạm y tế phường Tây Hồ",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Tây Hồ, Thành phố Hà Nội",
    phone: "",
    coords: [21.0642, 105.8141],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-tay-mo",
    name: "Trạm y tế phường Tây Mỗ",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Tây Mỗ, Thành phố Hà Nội",
    phone: "",
    coords: [20.9972, 105.7441],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-tay-phuong",
    name: "Trạm y tế xã Tây Phương",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Tây Phương, Thành phố Hà Nội",
    phone: "",
    coords: [21.0542, 105.6141],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-tay-tuu",
    name: "Trạm y tế phường Tây Tựu",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Tây Tựu, Thành phố Hà Nội",
    phone: "",
    coords: [21.0642, 105.7241],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-thach-that",
    name: "Trạm y tế xã Thạch Thất",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Thạch Thất, Thành phố Hà Nội",
    phone: "",
    coords: [21.0612, 105.5712],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-thanh-liet",
    name: "Trạm y tế phường Thanh Liệt",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Thanh Liệt, Thành phố Hà Nội",
    phone: "",
    coords: [20.9712, 105.8141],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-thanh-oai",
    name: "Trạm y tế xã Thanh Oai",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Thanh Oai, Thành phố Hà Nội",
    phone: "",
    coords: [20.8542, 105.7741],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-thanh-tri",
    name: "Trạm y tế xã Thanh Trì",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Thanh Trì, Thành phố Hà Nội",
    phone: "",
    coords: [20.9333,105.8505],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-thanh-xuan",
    name: "Trạm y tế phường Thanh Xuân",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Thanh Xuân, Thành phố Hà Nội",
    phone: "",
    coords: [20.9942, 105.8112],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-thien-loc",
    name: "Trạm y tế xã Thiên Lộc",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Thiên Lộc, Thành phố Hà Nội",
    phone: "",
    coords: [20.8142, 105.9041],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-thu-lam",
    name: "Trạm y tế xã Thư Lâm",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Thư Lâm, Thành phố Hà Nội",
    phone: "",
    coords: [21.1542, 105.9241],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-thuan-an",
    name: "Trạm y tế xã Thuận An",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Thuận An, Thành phố Hà Nội",
    phone: "",
    coords: [21.0142, 105.9841],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-thuong-cat",
    name: "Trạm y tế phường Thượng Cát",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Thượng Cát, Thành phố Hà Nội",
    phone: "",
    coords: [21.0942, 105.7241],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-thuong-phuc",
    name: "Trạm y tế xã Thượng Phúc",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Thượng Phúc, Thành phố Hà Nội",
    phone: "",
    coords: [20.8242, 105.7341],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-thuong-tin",
    name: "Trạm y tế xã Thường Tín",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Thường Tín, Thành phố Hà Nội",
    phone: "",
    coords: [20.8742, 105.8641],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-tien-thang",
    name: "Trạm y tế xã Tiến Thắng",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Tiến Thắng, Thành phố Hà Nội",
    phone: "",
    coords: [21.2442, 105.7141],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-tran-phu",
    name: "Trạm y tế xã Trần Phú",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Trần Phú, Thành phố Hà Nội",
    phone: "",
    coords: [20.8942, 105.6541],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-trung-gia",
    name: "Trạm y tế xã Trung Giã",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Trung Giã, Thành phố Hà Nội",
    phone: "",
    coords: [21.3142, 105.8841],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-tu-liem",
    name: "Trạm y tế phường Từ Liêm",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Từ Liêm, Thành phố Hà Nội",
    phone: "",
    coords: [21.0442, 105.7541],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-tung-thien",
    name: "Trạm y tế phường Tùng Thiện",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Tùng Thiện, Thành phố Hà Nội",
    phone: "",
    coords: [21.1312, 105.5072],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-tuong-mai",
    name: "Trạm y tế phường Tương Mai",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Tương Mai, Thành phố Hà Nội",
    phone: "",
    coords: [20.9912, 105.8541],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-ung-hoa",
    name: "Trạm y tế xã Ứng Hòa",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Ứng Hòa, Thành phố Hà Nội",
    phone: "",
    coords: [20.8542, 105.7641],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-ung-thien",
    name: "Trạm y tế xã Ứng Thiên",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Ứng Thiên, Thành phố Hà Nội",
    phone: "",
    coords: [20.7842, 105.8241],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-van-dinh",
    name: "Trạm y tế xã Vân Đình",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Vân Đình, Thành phố Hà Nội",
    phone: "",
    coords: [20.8342, 105.7641],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-van-mieu",
    name: "Trạm y tế phường Văn Miếu",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Văn Miếu, Thành phố Hà Nội",
    phone: "",
    coords: [21.0272, 105.8341],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-vat-lai",
    name: "Trạm y tế xã Vật Lại",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Vật Lại, Thành phố Hà Nội",
    phone: "",
    coords: [21.2142, 105.3741],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-viet-hung",
    name: "Trạm y tế phường Việt Hưng",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Việt Hưng, Thành phố Hà Nội",
    phone: "02438271222",
    coords: [21.0532, 105.9012],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-vinh-hung",
    name: "Trạm y tế phường Vĩnh Hưng",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Vĩnh Hưng, Thành phố Hà Nội",
    phone: "",
    coords: [20.9842, 105.8812],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-vinh-thanh",
    name: "Trạm y tế xã Vinh Thanh",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Vinh Thanh, Thành phố Hà Nội",
    phone: "",
    coords: [21.2642, 105.5141],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-vinh-tuy",
    name: "Trạm y tế phường Vĩnh Tuy",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Vĩnh Tuy, Thành phố Hà Nội",
    phone: "",
    coords: [20.9972, 105.8741],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-xuan-dinh",
    name: "Trạm y tế phường Xuân Đỉnh",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Xuân Đỉnh, Thành phố Hà Nội",
    phone: "",
    coords: [21.0742, 105.7841],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-xuan-mai",
    name: "Trạm y tế xã Xuân Mai",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Xuân Mai, Thành phố Hà Nội",
    phone: "",
    coords: [20.8942, 105.5841],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-xuan-phuong",
    name: "Trạm y tế phường Xuân Phương",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Xuân Phương, Thành phố Hà Nội",
    phone: "",
    coords: [21.0342, 105.7341],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-yen-bai",
    name: "Trạm y tế xã Yên Bài",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Yên Bài, Thành phố Hà Nội",
    phone: "",
    coords: [21.0642, 105.4541],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-yen-hoa",
    name: "Trạm y tế phường Yên Hòa",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Yên Hòa, Thành phố Hà Nội",
    phone: "",
    coords: [21.0242, 105.7941],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-yen-lang",
    name: "Trạm y tế xã Yên Lãng",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Yên Lãng, Thành phố Hà Nội",
    phone: "",
    coords: [21.1942, 105.7241],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-yen-nghia",
    name: "Trạm y tế phường Yên Nghĩa",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Yên Nghĩa, Thành phố Hà Nội",
    phone: "02433570221",
    coords: [20.9442, 105.7541],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-yen-so",
    name: "Trạm y tế phường Yên Sở",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phường Yên Sở, Thành phố Hà Nội",
    phone: "02438611445",
    coords: [20.9742, 105.8641],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-yen-xuan",
    name: "Trạm y tế xã Yên Xuân",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Yên Xuân, Thành phố Hà Nội",
    phone: "",
    coords: [21.2842, 105.4841],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
];
